import {
  BarChart3,
  BellRing,
  BookOpen,
  ClipboardList,
  FileText,
  FolderTree,
  GraduationCap,
  History,
  Landmark,
  Layers,
  LayoutDashboard,
  ListOrdered,
  MapPin,
  MapPinned,
  MessageSquareText,
  Package,
  PackageCheck,
  PackageSearch,
  Repeat2,
  ShieldCheck,
  SlidersHorizontal,
  TriangleAlert,
  Truck,
  Wallet,
  Warehouse,
  Users,
} from "lucide-react";

// Les 26 onglets admin. Module neutre (pas de "use client") : importé aussi
// bien par des composants serveur (app/admin/plus/page.tsx) que client
// (AdminNav, RechercheAllerA) — faire traverser un tableau contenant des
// références de composants depuis un fichier "use client" vers un composant
// serveur plante au runtime même si le build passe, d'où ce fichier séparé.
export const LIENS = [
  { href: "/admin", label: "Tableau de bord", icon: LayoutDashboard },
  { href: "/admin/livraisons", label: "Livraisons", icon: Truck },
  { href: "/admin/preparations", label: "Préparations", icon: PackageCheck },
  { href: "/admin/commandes", label: "Commandes", icon: ClipboardList },
  { href: "/admin/produits", label: "Produits", icon: Package },
  { href: "/admin/prix-a-verifier", label: "Prix à vérifier", icon: TriangleAlert },
  { href: "/admin/editions", label: "Éditions", icon: History },
  { href: "/admin/classement", label: "Classement accueil", icon: ListOrdered },
  { href: "/admin/moderation", label: "Modération vendeurs", icon: ShieldCheck },
  { href: "/admin/categories", label: "Catégories", icon: FolderTree },
  { href: "/admin/attributs", label: "Attributs", icon: SlidersHorizontal },
  { href: "/admin/synonymes", label: "Synonymes", icon: Repeat2 },
  { href: "/admin/recherches", label: "Ce que les clients cherchent", icon: PackageSearch },
  { href: "/admin/modeles", label: "Modèles de messages", icon: MessageSquareText },
  { href: "/admin/notifications", label: "Notifications", icon: BellRing },
  { href: "/admin/kits", label: "Kits", icon: GraduationCap },
  { href: "/admin/classes", label: "Classes", icon: Layers },
  { href: "/admin/ebooks", label: "Ebooks", icon: BookOpen },
  { href: "/admin/documents", label: "Notices de kits", icon: FileText },
  { href: "/admin/zones", label: "Groupes de livraison", icon: MapPin },
  { href: "/admin/localites", label: "Localités", icon: MapPinned },
  { href: "/admin/lieux-speciaux", label: "Lieux spéciaux", icon: Landmark },
  { href: "/admin/fournisseurs", label: "Fournisseurs", icon: Warehouse },
  { href: "/admin/ventes", label: "Articles vendus", icon: BarChart3 },
  { href: "/admin/clients", label: "Clients", icon: Users },
  { href: "/admin/comptabilite", label: "Comptabilité", icon: Wallet },
] as const;
